name: Build Geode Mod

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Windows
            os: windows-latest
          - name: Android32
            os: ubuntu-latest
            target: armv7-none-linux-androideabi
          - name: Android64
            os: ubuntu-latest
            target: aarch64-none-linux-android

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - data_type: checkout
        uses: actions/checkout@v4

      - name: Build Mod
        uses: geode-sdk/build-geode-mod@main
        with:
          bindings: geode-sdk/bindings
          target: ${{ matrix.config.target }}
          
